development:
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: blog_rails_development
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  username: root
  password:
  encoding: utf8
  database: blog_rails_test

production:
  adapter: mysql2
  encoding: unicode
  database: blog_rails_production
  pool: 5
